spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/schema_information
    hikari:
      max-lifetime: 10000
      idle-timeout: 300000
      connection-test-query: select 1
mysql-utils:
  output:
    path: D://temp
    filename: dbinfo.txt
  predicate:
    database:
      # include the databases, such as 'db1,db2,...', the * indicates all databases.
      include: pboc
      charset:
        - utf8
        - utf8mb4
      engin:
        innodb
    table:
      # include the tables, such as 'table1,table2,...', the * indicates all tables.
      include: *
      charset:
        - utf8
        - utfmb4
      rowformat:
        default
    column:
      # include the columns, such as 'table1,table2,...', the * indicates all tables.
      include: *
      flagLen:
        - 1
        - 2
