server:
  port:
    8080
debug:
  false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test
    hikari:
      max-lifetime: 10000
      idle-timeout: 300000
      connection-test-query: select 1
# middle config
middle:
  server: aaa
  # redis
  etcd:
    host: 127.0.0.1
    port: 2379
    password: 123456
    timeout: 1000