server:
  port:
    8081
debug:
  false
spring:
  application:
    name: spring-boot-jpa-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.177:33306/spring-boot-jpa?charset=utf8mb4&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    # 这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    # 配置指明在程序启动的时候要删除并且创建实体类对应的表
#    hibernate:
#      ddl-auto: create

# middle config
middle:
  server: aaa
  # redis
  etcd:
    host: 127.0.0.1
    port: 2379
    password: 123456
    timeout: 1000