server:
  port: 18080
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: swagger_demo_get_route
          uri: http://swager-service:8088
          predicates:
            - Path=/demo/**
eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:7001/eureka
      register-with-eureka: true
      fetch-register: true
